name: Continuous Integration

on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Test
        run: make test
